checks:
    php:
        code_rating: true
        duplication: true
        excluded_dependencies:
            - magento/*

filter: 
    excluded_paths:
         - vendor

build:
    environment:
            php:
                version: 8.1
    dependencies:
        before:
            - 'echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run