<?php
/*
 * Copyright Pure Mashiro. All rights reserved.
 * @author Mana Light
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\View\Element\Template $block */

$scriptString = '
    var BASE_URL = \'' . /* @noEscape */ $block->escapeJs($block->getBaseUrl()) . '\';
    var require = {
        \'baseUrl\': \'' . /* @noEscape */ $block->escapeJs($block->getViewFileUrl('/')) . '\'
    };';

echo /* @noEscape */ $secureRenderer->renderTag('script', ['type' => ' text/javascript'], $scriptString, false);
