name: 🚀 I want a new feature
description: Tell us what you want to see here.
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - elisei
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to complete this new feature request report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we contact you if we need more information?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What new feature do you want to see?
      description: Tell us also what you expected to happen and what the result will be!
      placeholder: Tell us what new feature you want!
    validations:
      required: true